<a href="https://colab.research.google.com/github/SriharshaVarmaC/Major-Crime-Indicators_Capstone-Project/blob/main/MCI_Cleaning%20and%20Exploring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Team Toronto Police MCI

#### Data Cleaning and Exploring

In [3]:
import pandas as pd

#### Loading the data and exploring

In [4]:
mci_df = pd.read_csv("Major_Crime_Indicators_Open_Data")
mci_df

,OBJECTID,EVENT_UNIQUE_ID,REPORT_DATE,OCC_DATE,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,...,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84,x,y
0,1,GO-20141263217,1/1/2014 5:00:00 AM,12/31/2013 5:00:00 AM,2014,January,1,1,Wednesday,16,...,Theft Of Motor Vehicle,Auto Theft,043,Victoria Village (43),043,Victoria Village (43),-79.306754,43.734654,-8.828387e+06,5.424471e+06
1,2,GO-20141260715,1/1/2014 5:00:00 AM,1/1/2014 5:00:00 AM,2014,January,1,1,Wednesday,3,...,Assault,Assault,092,Corso Italia-Davenport (92),092,Corso Italia-Davenport (92),-79.455770,43.677775,-8.844976e+06,5.415712e+06
2,3,GO-20141260730,1/1/2014 5:00:00 AM,1/1/2014 5:00:00 AM,2014,January,1,1,Wednesday,3,...,Assault,Assault,105,Lawrence Park North (105),105,Lawrence Park North (105),-79.406223,43.727681,-8.839460e+06,5.423396e+06
3,4,GO-20141260597,1/1/2014 5:00:00 AM,1/1/2014 5:00:00 AM,2014,January,1,1,Wednesday,2,...,Assault,Assault,080,Palmerston-Little Italy (80),080,Palmerston-Little Italy (80),-79.415594,43.654946,-8.840503e+06,5.412199e+06
4,5,GO-20141259762,1/1/2014 5:00:00 AM,12/31/2013 5:00:00 AM,2014,January,1,1,Wednesday,2,...,Assault,Assault,164,Wellington Place (164),077,Waterfront Communities-The Island (77),-79.390786,43.649125,-8.837742e+06,5.411303e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420195,420196,GO-20242816627,12/31/2024 5:00:00 AM,12/24/2024 5:00:00 AM,2024,December,31,366,Tuesday,10,...,Theft Of Motor Vehicle,Auto Theft,033,Clanton Park (33),033,Clanton Park (33),-79.449706,43.734062,-8.844301e+06,5.424380e+06
420196,420197,GO-20242815828,12/31/2024 5:00:00 AM,12/30/2024 5:00:00 AM,2024,December,31,366,Tuesday,7,...,Theft Of Motor Vehicle,Auto Theft,025,Glenfield-Jane Heights (25),025,Glenfield-Jane Heights (25),-79.513210,43.739385,-8.851370e+06,5.425200e+06
420197,420198,GO-20242814680,12/31/2024 5:00:00 AM,12/31/2024 5:00:00 AM,2024,December,31,366,Tuesday,2,...,Robbery - Mugging,Robbery,168,Downtown Yonge East (168),075,Church-Yonge Corridor (75),-79.378304,43.656258,-8.836352e+06,5.412401e+06
420198,420199,GO-20242815237,12/31/2024 5:00:00 AM,12/31/2024 5:00:00 AM,2024,December,31,366,Tuesday,4,...,B&E,Break and Enter,032,Englemount-Lawrence (32),032,Englemount-Lawrence (32),-79.433324,43.719406,-8.842477e+06,5.422122e+06
420199,420200,GO-20242815267,12/31/2024 5:00:00 AM,12/31/2024 5:00:00 AM,2024,December,31,366,Tuesday,4,...,B&E,Break and Enter,081,Trinity-Bellwoods (81),081,Trinity-Bellwoods (81),-79.418846,43.644170,-8.840865e+06,5.410541e+06

### Information about the data to get better idea
#### It has 420200 rowa and 31 columns (99.5)

In [5]:
print(mci_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420200 entries, 0 to 420199
Data columns (total 31 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   OBJECTID           420200 non-null  int64
 1   EVENT_UNIQUE_ID    420200 non-null  object
 2   REPORT_DATE        420200 non-null  object
 3   OCC_DATE           420200 non-null  object
 4   REPORT_YEAR        420200 non-null  int64
 5   REPORT_MONTH       420200 non-null  object
 6   REPORT_DAY         420200 non-null  int64
 7   REPORT_DOY         420200 non-null  int64
 8   REPORT_DOW         420200 non-null  object
 9   REPORT_HOUR        420200 non-null  int64
 10  OCC_YEAR           420056 non-null  float64
 11  OCC_MONTH          420056 non-null  object
 12  OCC_DAY            420056 non-null  float64
 13  OCC_DOY            420056 non-null  float64
 14  OCC_DOW            420056 non-null  object
 15  OCC_HOUR           420200 non-null  int64
 16  DIVISION           420200 non-null  object
 17  LOCATION_TYPE      420200 non-null  object
 18  PREMISES_TYPE      420200 non-null  object
 19  UCR_CODE           420200 non-null  int64
 20  UCR_EXT            420200 non-null  int64
 21  OFFENCE            420200 non-null  object
 22  MCI_CATEGORY       420200 non-null  object
 23  HOOD_158           420200 non-null  object
 24  NEIGHBOURHOOD_158  420200 non-null  object
 25  HOOD_140           420200 non-null  object
 26  NEIGHBOURHOOD_140  420200 non-null  object
 27  LONG_WGS84         420200 non-null  float64
 28  LAT_WGS84          420200 non-null  float64
 29  x                  420200 non-null  float64
 30  y                  420200 non-null  float64
dtypes: float64(7), int64(8), object(16)
memory usage: 99.4+ MB
None

#### Checking if data has null values

In [6]:
print(mci_df.isnull().sum())

OBJECTID               0
EVENT_UNIQUE_ID        0
REPORT_DATE            0
OCC_DATE               0
REPORT_YEAR            0
REPORT_MONTH           0
REPORT_DAY             0
REPORT_DOY             0
REPORT_DOW             0
REPORT_HOUR            0
OCC_YEAR             144
OCC_MONTH            144
OCC_DAY              144
OCC_DOY              144
OCC_DOW              144
OCC_HOUR               0
DIVISION               0
LOCATION_TYPE          0
PREMISES_TYPE          0
UCR_CODE               0
UCR_EXT                0
OFFENCE                0
MCI_CATEGORY           0
HOOD_158               0
NEIGHBOURHOOD_158      0
HOOD_140               0
NEIGHBOURHOOD_140      0
LONG_WGS84             0
LAT_WGS84              0
x                      0
y                      0
dtype: int64

In [7]:
#Checking % of null values
print(144/420200)

0.00034269395525940026

In [8]:
clean_mci_df = mci_df.dropna()

In [10]:
print(clean_mci_df.isnull().sum())

OBJECTID             0
EVENT_UNIQUE_ID      0
REPORT_DATE          0
OCC_DATE             0
REPORT_YEAR          0
REPORT_MONTH         0
REPORT_DAY           0
REPORT_DOY           0
REPORT_DOW           0
REPORT_HOUR          0
OCC_YEAR             0
OCC_MONTH            0
OCC_DAY              0
OCC_DOY              0
OCC_DOW              0
OCC_HOUR             0
DIVISION             0
LOCATION_TYPE        0
PREMISES_TYPE        0
UCR_CODE             0
UCR_EXT              0
OFFENCE              0
MCI_CATEGORY         0
HOOD_158             0
NEIGHBOURHOOD_158    0
HOOD_140             0
NEIGHBOURHOOD_140    0
LONG_WGS84           0
LAT_WGS84            0
x                    0
y                    0
dtype: int64

In [13]:
cleaned_file_path = "cleaned_data_mci.csv"
clean_mci_df.to_csv(cleaned_file_path, index=False)

print(f"Cleaned file saved as {cleaned_file_path}")

Cleaned file saved as cleaned_data_mci.csv